Completed Phase 1 - Logan Lee
loganlee-lth/c0523-code-solutions pull request #89
Opened 2023-06-28 19:09 UTC by loganlee-lth

<img width="1512" alt="Screen Shot 2023-06-28 at 12 07 04 PM" src="https://github.com/loganlee-lth/c0523-code-solutions/assets/36302145/7acde51b-0f84-4cd4-a8fe-9575d5d98de9">

2023-06-28 19:13 UTC, TimelikeClosure requested changes
@loganlee-lth Phase 1 looks good, looking forward to Phase 2.

2023-06-28 19:13 UTC, TimelikeClosure commented on react-design/my-app/src/RotatingBanner.css
> +}
I'd suggest importing this style directly into the `Indicators` component, since that's the only component that uses it.

2023-06-28 21:41 UTC, TimelikeClosure requested changes
@loganlee-lth Don't forget to highlight the indicator button for the item you're currently on:

---

![image](https://github.com/loganlee-lth/c0523-code-solutions/assets/16143771/f5e59091-690c-4e3d-b83e-622a4c6a4dbc)

2023-06-29 13:20 UTC, loganlee-lth commented
![Kapture 2023-06-29 at 06 17 55](https://github.com/loganlee-lth/c0523-code-solutions/assets/36302145/522bf45a-249a-4efc-9eb6-e930ed867c22)

2023-06-29 16:20 UTC, TimelikeClosure approved these changes

2023-06-30 00:00 UTC, merged